### ISSUE TITLE
Questions regarding this project.

### ISSUE THREAD

**Issue by chainloaded** [bielu000/pe-dumper#1]
Since I couldn't find a way to directly contact you I'm trying to reach out to you this way. 
I'm currently learning about process injection on Windows and I want to inject an exe file into a process and use AddressOfEntryPoint of the executable as start for the remote process. I found a question of you regarding this topic (https://www.kernelmode.info/forum/viewtopic0b77.html?t=5179) and was wondering if you could share the "adjust_imports" function in your provided code. 

I apologize for the inconvenience.

**Comment by pblxptr** [comment]
Hello, I barely remember this project, because it has been developed a few years ago(and it was just a proof of concept), but I did a quick look at the code, and it seems that the function you are looking for is placed on branch called "feature". Here is a direct link: https://github.com/bielu000/Portable-Executable-Injector-Sample/blob/feature/PeDumper/PeDumper.c

**Comment by chainloaded** [comment]
Thank you! I really appreciate it.

**Comment by pblxptr** [comment]
Done.
